#title:              Clean Blog
title:              Zappa
email:              francesco.zappa1@gmail.com
  #description:        A Blog Theme by Start Bootstrap
description:        Frank
  #author:             Start Bootstrap
author:             Francesco
template:           startbootstrap-clean-blog-jekyll
baseurl:            ""
url:                "https://frazz11.github.io"

# Social Profiles
twitter_username:   #SBootstrap
github_username:    frazz11
facebook_username:  #StartBootstrap
instagram_username:  
linkedin_username:  francesco-zappa-13545922b

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
